### ISSUE TITLE
Reading MySQL fails

### ISSUE THREAD

**Issue by kikelkik** [AngrySoundTech/CouponCodes#22]
I'm running CouponCodes 3.2 on Spigot.
The plugin works well (also /coupon redeem) until it comes to an error, if I do the /coupon redeem-command: http://dev.bukkit.org/paste/is3nlqa0e9hy1w6k/
From this point on, the error persists whenever I try to access the MySQL database with CouponCodes. 
/coupon list as well: http://dev.bukkit.org/paste/xbprld97jm1fkeay/

After a server-restart, everything works well a few hours...the error does not appear every day at the same time.

Thanks for your help :)

kikelkik

**Comment by Drepic26** [comment]
I believe that your MySQL server is implicitly closing the connection, because it has been inactive for too long a time. Could you try adjusting/removing the connection timeout on MySQL server-side, then seeing if the issue persists?

**Comment by Drepic26** [comment]
If this is the case, I'll have to implement a connection test on the plugin's end

**Comment by kikelkik** [comment]
Thank you for answering quickly! 
I changed the DBMS connection read time out from 600 seconds to 0 - I don't think there is an option called "connection timeout" on MySQL Workbench.

But unfortunately, the error perists: http://dev.bukkit.org/paste/fq7icsge9krjpy2a/

I would'nt claim that this is not caused by settings on MySQL Workbench, but I didn't changed anything besides the connection read time out on Monday.

**Comment by Drepic26** [comment]
I'm going to set up a test environment and attempt to reproduce this error.

**Comment by Drepic26** [comment]
Could you provide a little more info?
* Server Software version
* Plugin Version
* MySQL Version

**Comment by kikelkik** [comment]
Server: Windows Server 2012 R2 Standard
Spigot version: 1.8.7-R0.1-SNAPSHOT (git-Spigot-44c59bf-a2d2640)
Plugin: CouponCodes 3.2
MySQL: 5.6.17-log

**Comment by Drepic26** [comment]
I've drafted a pre-release which should fix these errors, Let me know if the errors still occur with this new version [3.2.1-SNAPSHOT 1](https://github.com/Drepic26/CouponCodes3/releases/tag/3.2.1-snapshot1)

**Comment by kikelkik** [comment]
Thanks a lot for your quick support!
I pulled the pre-release on my server - hopefully, the error is banned from now on. If not, I'll inform you :)
